version: "3.1"

services:
  db:
    container_name: postgres-student-db
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    deploy:
      mode: global
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_student_data:/var/lib/postgresql/data

  api:
    container_name: student-api
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_DATASOURCE_DRIVERCLASSNAME: ${DATABASE_DRIVER_CLASS_NAME}
      SPRING_JPA_HIBERNATE_DDL-AUTO: ${SPRING_DATA_JPA_DDL}
      SPRING_JPA_DATABASE: ${SPRING_DATA_JPA_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      URI_BASE_LIBRARY: ${URI_BASE_LIBRARY}
      URI_BASE_FINANCE: ${URI_BASE_FINANCE}
    volumes:
      - student_api:/app
    networks:
      - default

  web:
    container_name: student-web
    build:
      context: ../../frontend/student
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      VITE_STUDENT_API_URL: ${VITE_STUDENT_API_URL}

volumes:
  postgres_student_data:
    driver: local
  student_api:
    driver: local

networks:
  default:
    external:
      name: lbu-sesc
