version: "3.1"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    deploy:
      mode: global
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgre_data:/var/lib/postgresql/data

  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      server.port: ${SERVER_PORT}
      spring.datasource.url: ${DATASOURCE_URL}/${DATABASE_NAME}
      spring.datasource.username: ${DATABASE_USER}
      spring.datasource.password: ${DATABASE_PASSWORD}
      spring.datasource.driver-class-name: ${DATABASE_DRIVER_CLASS_NAME}
      spring.jpa.hibernate.ddl-auto: ${SPRING_DATA_JPA_DDL}
      spring.jpa.show-sql: ${SPRING_SHOW_SQL}
      spring.jpa.database: ${SPRING_DATA_JPA_DATABASE}
      spring.jpa.database-platform: ${SPRING_DATABASE_PLATFORM}
      jwt.secret: ${JWT_SECRET}

volumes:
  postgre_data:
    driver: local
