version: '3.1'

services:
  db:
    container_name: mongo-db
    image: mongo
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - '27017:27017'

  api:
    container_name: finance-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - db
    environment:
      PORT: ${PORT}
      MONGO_DB_CONNECTION_URL: ${MONGO_DB_CONNECTION_URL_DOCKER}
      MONGO_DB_CONNECTION_PASSWORD: ${MONGO_DB_CONNECTION_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_DB_USER_NAME: ${MONGO_DB_USER_NAME}
      PASSWORD_SALT_ROUNDS: ${PASSWORD_SALT_ROUNDS}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - finance_api:/app

volumes:
  mongo_db:
    driver: local
  finance_api:
    driver: local
