version: "3.1"

services:
  db:
    container_name: postgres-library-db
    image: postgres
    ports:
      - "5433:5432"
    expose:
      - "5433"
    deploy:
      mode: global
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_library_data:/var/lib/postgresql/data

  api:
    container_name: library-api
    build:
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_DATASOURCE_DRIVERCLASSNAME: ${DATABASE_DRIVER_CLASS_NAME}
      SPRING_JPA_HIBERNATE_DDL-AUTO: ${SPRING_DATA_JPA_DDL}
      SPRING_JPA_DATABASE: ${SPRING_DATA_JPA_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - library_api:/app
    networks:
      - default

volumes:
  postgres_library_data:
    driver: local
  library_api:
    driver: local

networks:
  default:
    external:
      name: lbu-sesc
